version: '3'
services:
  app:
    image: dalmiamanhv/sensai-ai:demos
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=staging
    ports:
      - '8001:8001'
    environment:
      - ENV=staging
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8001

  demo:
    image: dalmiamanhv/sensai-ai:demos
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=staging
    ports:
      - '8501:8501'
    working_dir: /demo
    command: streamlit run app.py
  
  english_demo:
    image: dalmiamanhv/sensai-ai:demos
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=staging
    ports:
      - '8502:8502'
    working_dir: /demo
    command: streamlit run english_new.py --server.port 8502
    volumes:
      - /appdata:/appdata

  english_activity:
    image: dalmiamanhv/sensai-ai:demos
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=staging
    ports:
      - '8503:8503'
    working_dir: /demo
    command: streamlit run english_activity.py --server.port 8503
    volumes:
      - /appdata:/appdata
